# -*- coding: utf-8 -*-
"""Remove_Background.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BxJchuf597QD_NMfsxXJKffUIoNQ3zLY
"""

!pip install rembg

from rembg import remove
from PIL import Image

input_path = 'cl.jpg'
output_path = 'output.png'

input = Image.open(input_path)
output = remove(input)
output.save(output_path)

